# Generated by Django 4.2.2 on 2023-06-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=9898989890, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='xyd', max_length=20),
        ),
    ]
