# Generated by Django 4.2.2 on 2023-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='vijay', max_length=20),
        ),
    ]
