# Generated by Django 4.2.2 on 2023-06-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_phone_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
